"""Builds the in-app user guide page: `npm run guide`.

Reads docs/USER_GUIDE.md, embeds its screenshots (compressed to WebP) as data URIs, and writes
src/webapp/guide/guide.html. The web app serves that page at <app url>?page=guide (see doGet.gs).
Re-run after editing the guide or regenerating the screenshots, then `clasp push`.
Needs Pillow (pip install pillow).
"""
import base64
import io
import json
import os
import re

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, 'docs')
OUT = os.path.join(ROOT, 'src', 'webapp', 'guide', 'guide.html')


def data_uri(path):
    img = Image.open(path).convert('RGB')
    buf = io.BytesIO()
    img.save(buf, 'WEBP', quality=80, method=6)
    return 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode('ascii')


def main():
    md = open(os.path.join(DOCS, 'USER_GUIDE.md'), encoding='utf-8').read()
    md = re.sub(r'\]\((images/[^)\s]+)\)', lambda m: '](' + data_uri(os.path.join(DOCS, m.group(1))) + ')', md)
    # JSON-encode for a <script> block; escape "</" so the guide text can never close the tag
    payload = json.dumps(md).replace('</', '<\\/')
    html = TEMPLATE.replace('__GUIDE_MARKDOWN__', payload)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w', encoding='utf-8', newline='\n').write(html)
    print('Wrote %s (%d KB)' % (os.path.relpath(OUT, ROOT), len(html) // 1024))


TEMPLATE = """<!DOCTYPE html>
<!-- GENERATED by tools/build-guide.py from docs/USER_GUIDE.md. Edit the Markdown, then run `npm run guide`. -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>User Guide</title>
<style>
:root{--ink:#1d2b3a;--dim:#5b6b7d;--line:#d5e0ec;--bg:#f4f7fa;--panel:#fff;--accent:#143452;--soft:#eef3f8;--link:#1f5f9e}
@media (prefers-color-scheme:dark){:root{--ink:#e4ebf2;--dim:#9fb0c2;--line:#2c3e52;--bg:#0f1823;--panel:#16222f;--accent:#9cc3ea;--soft:#1c2b3b;--link:#8fc0f0}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.65 "Segoe UI",Roboto,Arial,sans-serif}
.bar{position:sticky;top:0;z-index:2;background:#143452;color:#fff;padding:12px 16px;display:flex;justify-content:space-between;align-items:center;gap:12px}
.bar b{font-size:15px}.bar a{color:#fff;font-size:14px;border:1px solid rgba(255,255,255,.5);border-radius:8px;padding:6px 12px;text-decoration:none;white-space:nowrap}
main{max-width:880px;margin:24px auto;padding:8px 28px 40px;background:var(--panel);border:1px solid var(--line);border-radius:12px}
h1{font-size:28px;color:var(--accent);margin:24px 0 4px}h2{font-size:23px;color:var(--accent);border-bottom:2px solid var(--line);padding-bottom:6px;margin-top:44px}
h3{font-size:19px;margin-top:32px}h4{font-size:16px;margin-top:24px}
a{color:var(--link)}
img{display:block;max-width:100%;height:auto;margin:16px 0 22px;border:1px solid var(--line);border-radius:8px;box-shadow:0 2px 10px rgba(0,0,0,.08)}
table{border-collapse:collapse;width:100%;margin:12px 0 18px;font-size:15px;display:block;overflow-x:auto}
th,td{border:1px solid var(--line);padding:7px 10px;text-align:left;vertical-align:top}th{background:var(--soft)}
blockquote{margin:16px 0;padding:10px 16px;background:var(--soft);border-left:4px solid var(--accent);border-radius:6px}blockquote p{margin:4px 0}
code{background:var(--soft);padding:1px 5px;border-radius:4px;font-size:90%}
hr{border:0;border-top:1px solid var(--line);margin:36px 0}
li{margin:3px 0}
#loading{color:var(--dim);padding:40px 0;text-align:center}
@media (max-width:640px){main{margin:0;border-radius:0;border-width:0;padding:4px 16px 32px}h1{font-size:24px}h2{font-size:20px}}
</style>
</head>
<body>
<div class="bar"><b>MSIC User Guide</b><a href="__APP_URL__" target="_top">Open the app</a></div>
<main id="guide"><p id="loading">Loading the guide&hellip;</p></main>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/4.3.0/marked.min.js"></script>
<script>
const GUIDE_MD = __GUIDE_MARKDOWN__;
(function () {
  const el = document.getElementById('guide');
  if (!window.marked) { el.innerHTML = '<p id="loading">The guide could not load. Check your internet connection and refresh.</p>'; return; }
  // Heading ids match the guide's contents links (GitHub-style slugs)
  el.innerHTML = marked.parse(GUIDE_MD, { headerIds: true, headerPrefix: '', mangle: false });
  document.querySelectorAll('#guide a[href^="#"]').forEach(a => a.addEventListener('click', e => {
    const t = document.getElementById(decodeURIComponent(a.getAttribute('href').slice(1)));
    if (t) { e.preventDefault(); t.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  }));
})();
</script>
</body>
</html>
"""

if __name__ == '__main__':
    main()
